FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY templates ./templates
COPY static ./static
COPY geojson ./geojson

EXPOSE 8003

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8003"]